### ISSUE TITLE
Add Initial Content

### ISSUE THREAD

**Issue by Hotdogdavid** [csctd/profile-website-Hotdogdavid#3]
- [ ] add a picture of a monkey
- [ ] add my resume or sum
- [ ] change the background

**Comment by Hotdogdavid** [comment]
![thingy](https://github.com/csctd/profile-website-Hotdogdavid/assets/141273652/1ff774af-47f9-4a2c-aeb5-bbbea1a14245)

**Comment by sarmenti7** [comment]
Nice work!
